import { __ } from '@wordpress/i18n';

const getContents = ( canMigrateSite, migrationUrl ) => {
	return {
		heading: __( 'Welcome to WordPress', 'wp-module-onboarding' ),
		subheading: __( 'powered by ', 'wp-module-onboarding' ),
		questionnaire: __(
			'Where would you like to start?',
			'wp-module-onboarding'
		),
		largerOption: {
			title: __( 'Site Creator', 'wp-module-onboarding' ),
			text1: __( 'Get a site created in seconds!', 'wp-module-onboarding' ),
			text2: __(
				'Content & design generated by AI, customizable by you.',
				'wp-module-onboarding'
			),
			span: __( 'AI', 'wp-module-onboarding' ),
			flow: 'sitegen',
		},
		smallerOptions: [
			{
				title: __( 'Guided Website Setup', 'wp-module-onboarding' ),
				subtitle: __(
					'Follow a step-by-step guide.',
					'wp-module-onboarding'
				),
				flow: 'sitebuild',
				show: true,
			},
			{
				title: __( 'Import a WordPress Site', 'wp-module-onboarding' ),
				subtitle: __(
					'Use our free, automated import tool!',
					'wp-module-onboarding'
				),
				flow: 'migration',
				show: canMigrateSite || migrationUrl,
			},
		],
		importtext: __(
			'Already have a WordPress site you want to import?',
			'wp-module-onboarding'
		),
		importlink: __(
			'https://my.bluehost.com/cgi/services/migration',
			'wp-module-onboarding'
		),
		exitToWordPress: __(
			'I’m following a tutorial, take me to the WP Admin Dashboard.',
			'wp-module-onboarding'
		),
	};
};

export default getContents;
