import { useRef, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Title } from '@newfold/ui-component-library';
import aiSiteGenIconUrl from '@/assets/ai-sitegen-icon.svg';
import ActionCard from '@/components/ActionCard/ActionCard';
import { OnboardingEvent, trackOnboardingEvent } from '@/utils/analytics/hiive';
import { ACTION_FORK_OPTION_SELECTED } from '@/utils/analytics/hiive/constants';

const SiteCreatorCard = ( { initialFocus = false } ) => {
	const cardRef = useRef( null );
	const navigate = useNavigate();

	// Focus the card if initialFocus is true
	useEffect( () => {
		if ( initialFocus ) {
			window.requestAnimationFrame( () => {
				if ( cardRef.current ) {
					cardRef.current.focus();
				}
			} );
		}
	}, [ initialFocus ] );

	const handleAction = () => {
		navigate( '/intake', {
			state: { direction: 'forward' },
			replace: false,
		} );

		// Analytics: site creator fork option selected event
		trackOnboardingEvent(
			new OnboardingEvent(
				ACTION_FORK_OPTION_SELECTED,
				'AI'
			)
		);
	};

	return (
		<ActionCard
			onClick={ handleAction }
			ref={ cardRef }
		>
			<div className="nfd-flex nfd-flex-col nfd-items-center nfd-justify-center nfd-text-center nfd-gap-5">
				<div className="nfd-flex nfd-items-center nfd-gap-3">
					<img
						src={ aiSiteGenIconUrl }
						alt={ __( 'AI Site Generator', 'wp-module-onboarding' ) }
					/>
					<span className="nfd-text-2xl nfd-font-medium nfd-text-[#423043]">
						{ __( 'Site Creator', 'wp-module-onboarding' ) }
					</span>
				</div>

				<div className="nfd-flex nfd-flex-col nfd-gap-2">
					<Title
						as="h3"
						className="nfd-text-xl nfd-font-medium nfd-text-content-primary mobile:nfd-text-lg"
					>
						{ __( 'Get a site created in seconds!', 'wp-module-onboarding' ) }
					</Title>
					<div className="nfd-flex nfd-flex-col nfd-text-[15px] nfd-text-content-primary">
						<span>
							{ __( 'Content & design generated by AI,', 'wp-module-onboarding' ) }
						</span>
						<br className="nfd-hidden" />
						<span>
							{ __( 'fully customizable by you.', 'wp-module-onboarding' ) }
						</span>
					</div>
				</div>
			</div>
		</ActionCard>
	);
};

export default SiteCreatorCard;
