export const LOGOGEN_STATES = {
	RECEIVED: 'recieved',
	GENERATING: 'generating',
	COMPLETED: 'completed',
	FAILED: 'failed',
};
export const PENDING_STATES = [ LOGOGEN_STATES.RECEIVED, LOGOGEN_STATES.GENERATING ];
export const RESOLVED_STATES = [ LOGOGEN_STATES.COMPLETED, LOGOGEN_STATES.FAILED ];
