export const LOGOGEN_STATES = {
	RECEIVED: 'received',
	DISCOVERY: 'discovery',
	GENERATING: 'generation',
	COMPLETED: 'completed',
	FAILED: 'failed',
};
export const INITIAL_STATES = [ LOGOGEN_STATES.RECEIVED, LOGOGEN_STATES.DISCOVERY ];
export const PENDING_STATES = [ LOGOGEN_STATES.RECEIVED, LOGOGEN_STATES.DISCOVERY, LOGOGEN_STATES.GENERATING ];
export const RESOLVED_STATES = [ LOGOGEN_STATES.COMPLETED, LOGOGEN_STATES.FAILED ];
